apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
spec:
  storageClassName:  do-block-storage-xfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
